### ISSUE TITLE
passing relative path to --farm option doesn't seem to work properly.

### ISSUE THREAD

**Issue by aris-koning** [MonetDBSolutions/tpch-scripts#1]
When I run  `./tpch_build.sh --sf 2--farm some_relative_path_to_farm` from within the `tcph-scripts` base directory, it actually creates a farm in the `02_load` subdirectory:

`tcph-scripts/02_load/some_relative_path_to_farm/SF-2`

Consider one of the following:

- document that `--farm` only accept absolute paths
- make sure relative paths also work for `--farm` and create the database where you expect it.
- disallow relative path in `--farm`.

**Comment by kutsurak** [comment]
I went with the first and third option. The usage message is now a bit more informative (hopefully) and gets printed when you pass a relative path as argument.
